version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    links:
      - dbpostgres

  dbpostgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: postgres