name: Berza service
on:
  push:
    branches:
      - '**' # matchuj sve brancheve, posto dosta koristimo feature brancheve (po defaultu je samo master)
    paths:
      - 'pom.xml'
      - 'berza/**'
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'pom.xml'
      - 'berza/**'
jobs:
  build:
    name: Build Berza service
    runs-on: ubuntu-latest
    steps:
      - uses: RAF-SI-2021/sonar-cloud-prep@v0.0.1
        with:
          java-version: 17
      - name: "[Berza] Build and analyze"
        working-directory: ./berza
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BERZA }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=rs.edu.raf.banka:berza -Dsonar.projectName="Banka_Berza_Service" sonar:sonar -Pcoverage

